[[bond]]
source = "tpknam1qq0d728hp5hd48cktwy4wt8n4jmr5fvujuv2x6hrp9h3dnzdnlkkyjyn40y"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "100"

[bond.signatures]
tpknam1qq0d728hp5hd48cktwy4wt8n4jmr5fvujuv2x6hrp9h3dnzdnlkkyjyn40y = "signam1qzqyf6uew0x9c3nuqrgacm5geqm0657cw8n2pxxzrn6rf5nmukftx4fq69fd7s8rse4whhqa83cnjr5awtvmzv22neq7jg94h2ay9hgfe3lasv"
